// ─── Analysis types ───────────────────────────────────────────────────────────

export type IssueSeverity = 'red' | 'yellow' | 'blue';

// ─── Conversation context types ───────────────────────────────────────────────

/** A single turn in a conversation (user prompt or AI response). */
export interface ConversationMessage {
  role: 'user' | 'assistant';
  content: string;
}

/** Stored context for a tab/session. Written to localStorage by session-context.ts */
export interface SessionContext {
  summary: string;           // LLM-generated 80-word summary
  promptCount: number;       // How many user prompts tracked since last scan
  lastUpdatedAt: number;     // timestamp
  sourceUrl: string;         // which chat page this came from
  scannedMessageCount: number; // how many messages were in scope at scan time
}

export type IssueCategory =
  | 'ambiguous_instructions'
  | 'missing_context'
  | 'conflicting_requirements'
  | 'vague_language'
  | 'unclear_objective'
  | 'missing_constraints'
  | 'poor_structure'
  | 'redundant_instructions'
  | 'incorrect_assumptions'
  | 'missing_output_format'
  | 'unspecified_audience'
  | 'unclear_tone'
  | 'hallucination_risk';

export interface IssueSpan {
  start: number;
  end: number;
}

export interface Issue {
  id: string; // generated client-side
  span: IssueSpan;
  category: IssueCategory;
  severity: IssueSeverity;
  explanation: string;
  suggestions: string[];
}

export interface AnalysisResult {
  issues: Issue[];
  overall_notes: string;
  analyzed_at: number; // timestamp
  prompt_hash: string;
}

// ─── Memory types ─────────────────────────────────────────────────────────────

export type MemoryKind = 'preference' | 'glossary' | 'project' | 'correction';

export interface MemoryEntry {
  id: string;
  user_id: string;
  project_id: string | null;
  kind: MemoryKind;
  content: string;
  created_at: string;
  last_used_at: string | null;
}

// ─── Extension messages (content ↔ service worker) ────────────────────────────

export type MessageType =
  | 'ANALYZE_REQUEST'
  | 'ANALYZE_RESPONSE'
  | 'IMPROVE_FULL_REQUEST'
  | 'IMPROVE_FULL_RESPONSE'
  | 'REFINE_REQUEST'
  | 'REFINE_RESPONSE'
  // ── Phase C: Scan Chat ──────────────────────────────────────────────────
  | 'SCAN_CONTEXT_REQUEST'    // popup → SW → backend: scan DOM messages
  | 'SCAN_CONTEXT_RESPONSE'   // backend → SW → popup: summary string
  // ── Phase B: Submit tracking ────────────────────────────────────────────
  | 'TRACK_PROMPT_REQUEST'    // content → SW → backend: new prompt submitted
  | 'TRACK_PROMPT_RESPONSE'   // backend → SW → content: updated summary
  | 'GET_SESSION_CONTEXT'     // popup → content: get current localStorage context
  | 'SESSION_CONTEXT_RESPONSE'// content → popup: SessionContext or null
  | 'CLEAR_SESSION_CONTEXT'   // popup → content: wipe localStorage context
  // ── Auth ────────────────────────────────────────────────────────────────
  | 'GET_MEMORIES'
  | 'MEMORIES_RESPONSE'
  | 'DELETE_MEMORY'
  | 'UPDATE_MEMORY'
  | 'FEEDBACK'
  | 'AUTH_STATE_CHANGE'
  | 'GET_AUTH_STATE'
  | 'AUTH_STATE_RESPONSE'
  | 'ERROR';

export interface ExtMessage<T = unknown> {
  type: MessageType;
  payload: T;
  requestId?: string;
}

export interface AnalyzeRequestPayload {
  text: string;
  changedSpan?: { start: number; end: number };
  sessionSummary?: string;
  /** Phase C/B: 80-word conversation context summary from session-context.ts */
  sessionContext?: string;
  projectId?: string | null;
  promptHash: string;
}

export interface ImproveFullRequestPayload {
  text: string;
  projectId?: string | null;
}

export interface RefineRequestPayload {
  fullText: string;
  spanStart: number;
  spanEnd: number;
  suggestion: string;
  category?: string;
}

export interface RefineResponse {
  refinedSuggestion: string;
}

// ─── Phase C: Scan context ────────────────────────────────────────────────────

export interface ScanContextRequestPayload {
  /** The last N conversation messages read from the DOM */
  messages: ConversationMessage[];
  /** Which site this came from, for logging */
  sourceUrl: string;
}

export interface ScanContextResponse {
  /** 80-word context summary generated by LLM */
  summary: string;
  /** How many messages were included */
  messageCount: number;
}

// ─── Phase B: Prompt tracking ─────────────────────────────────────────────────

export interface TrackPromptRequestPayload {
  /** The user's prompt that was just submitted */
  prompt: string;
  /** Session ID (tab-scoped, from localStorage) */
  sessionId: string;
  /** Current summary, used as base for incremental update */
  currentSummary: string;
  promptCount: number;
}

export interface TrackPromptResponse {
  /** Updated summary (re-generated every 3 prompts, passthrough otherwise) */
  summary: string;
  promptCount: number;
}

export interface ImproveFullResponse {
  rewritten: string;
  rationale: string;
  diff: DiffChunk[];
}

export interface DiffChunk {
  type: 'equal' | 'insert' | 'delete';
  value: string;
}

export interface FeedbackPayload {
  suggestionId: string;
  accepted: boolean;
  category: IssueCategory;
}

// ─── Auth state ───────────────────────────────────────────────────────────────

export interface AuthState {
  isAuthenticated: boolean;
  userId: string | null;
  email: string | null;
  accessToken: string | null;
}

// ─── Extension settings ───────────────────────────────────────────────────────

export interface ExtensionSettings {
  analysisEnabled: boolean;
  memoryEnabled: boolean;
  modelSpeed: 'fast' | 'quality';
  privacyMode: boolean; // no cloud calls for this project
  activeProjectId: string | null;
}

export const DEFAULT_SETTINGS: ExtensionSettings = {
  analysisEnabled: true,
  memoryEnabled: true,
  modelSpeed: 'quality',
  privacyMode: false,
  activeProjectId: null,
};
